import React,{useState,useRef,useEffect} from 'react';
import {Upload,Plus,X,Download,Trash2,Lock,HardDrive,LoaderCircle,Info,ArrowRightLeft,ShieldCheck,ChevronDown,FileText,Image as ImageIcon,AudioLines,Clapperboard,Check} from 'lucide-react';
import {categories,formatNames,bytes} from './catalog';
import {convertFile} from './convert';
import {validateBatch,BATCH_LIMIT,uniqueNames} from './batch';
const icons={documents:FileText,images:ImageIcon,audio:AudioLines,video:Clapperboard};
export default function Converter({kind,onBusy,showFormats}){
 const [items,setItems]=useState([]),[target,setTarget]=useState(categories[kind].outputs[0]),[quality,setQuality]=useState('balanced'),[busy,setBusy]=useState(false),[zipBusy,setZipBusy]=useState(false),[zip,setZip]=useState(null),[status,setStatus]=useState(''),[error,setError]=useState(''),[dragging,setDragging]=useState(false);
 const input=useRef(null),queue=useRef([]),controller=useRef(null),generation=useRef(0),working=useRef(false),zipRef=useRef(null),actions=useRef(null),nextId=useRef(0);
 const config=categories[kind],Icon=icons[kind],total=items.reduce((n,x)=>n+x.file.size,0),ready=items.filter(x=>x.result),pending=items.filter(x=>!x.result);
 function update(next){queue.current=typeof next==='function'?next(queue.current):next;setItems(queue.current);}
 function clearZip(){if(zipRef.current)URL.revokeObjectURL(zipRef.current.url);zipRef.current=null;setZip(null);}
 function releaseResults(){clearZip();update(rows=>rows.map(x=>{if(x.result)URL.revokeObjectURL(x.result.url);return{...x,result:null,state:'waiting',error:''};}));}
 function clear(){generation.current++;controller.current?.abort();working.current=false;onBusy(false);setBusy(false);setZipBusy(false);clearZip();for(const x of queue.current)if(x.result)URL.revokeObjectURL(x.result.url);update([]);setStatus('');setError('');}
 function add(files){if(working.current)return;try{const list=validateBatch(queue.current.map(x=>x.file),files,kind);clearZip();setError('');setStatus('');update(rows=>[...rows,...list.map(file=>({id:`file-${++nextId.current}`,file,state:'waiting',error:'',result:null}))]);}catch(e){setError(e.message);}}
 function remove(id){if(working.current)return;clearZip();const row=queue.current.find(x=>x.id===id);if(row?.result)URL.revokeObjectURL(row.result.url);update(rows=>rows.filter(x=>x.id!==id));setError('');}
 function cancel(){generation.current++;controller.current?.abort();controller.current=null;working.current=false;setBusy(false);onBusy(false);update(rows=>rows.map(x=>x.state==='converting'?{...x,state:'waiting'}:x));setStatus('Stopped. Completed files are ready; remaining files can be resumed.');}
 async function start(){
  if(working.current)return;const waiting=queue.current.filter(x=>!x.result);if(!waiting.length)return;
  const id=++generation.current;const aborter=new AbortController();controller.current=aborter;working.current=true;setBusy(true);onBusy(true);setError('');clearZip();
  let completed=0,failed=0;
  for(let i=0;i<waiting.length;i++){
   if(aborter.signal.aborted||id!==generation.current)break;const item=waiting[i];
   update(rows=>rows.map(x=>x.id===item.id?{...x,state:'converting',error:''}:x));
   try{
    const blob=await convertFile(item.file,kind,target,{signal:aborter.signal,quality,onStatus:s=>{if(id===generation.current)setStatus(`File ${i+1} of ${waiting.length} · ${s}`);}});
    if(aborter.signal.aborted||id!==generation.current)break;
    const result={blob,url:URL.createObjectURL(blob),name:item.file.name.replace(/\.[^.]+$/,'')+'.'+target,size:blob.size,type:blob.type};
    update(rows=>rows.map(x=>x.id===item.id?{...x,state:'done',result}:x));completed++;
   }catch(e){if(aborter.signal.aborted||id!==generation.current)break;failed++;update(rows=>rows.map(x=>x.id===item.id?{...x,state:'error',error:e.name==='PasswordException'?'Password-protected PDF. Use an unlocked copy.':e.message||'Could not convert this file.'}:x));}
  }
  if(id===generation.current){setStatus(`${completed} converted${failed?` · ${failed} failed. Check the affected files below.`:'. Your downloads are ready.'}`);setBusy(false);onBusy(false);working.current=false;controller.current=null;}
 }
 async function prepareZip(){if(working.current)return;const selected=queue.current.filter(x=>x.result);if(!selected.length)return;const id=++generation.current;working.current=true;onBusy(true);setZipBusy(true);setError('');
  try{const {default:JSZip}=await import('jszip');const archive=new JSZip();const names=uniqueNames(selected.map(x=>x.result.name));for(let i=0;i<selected.length;i++)archive.file(names[i],await selected[i].result.blob.arrayBuffer());const blob=await archive.generateAsync({type:'blob',compression:'STORE'},meta=>{if(id===generation.current)setStatus(`Preparing ZIP · ${Math.round(meta.percent)}%`);});if(id!==generation.current)return;const next={url:URL.createObjectURL(blob),size:blob.size};zipRef.current=next;setZip(next);setStatus('Your ZIP is ready.');}catch(e){if(id===generation.current)setError('Could not package the files. Download them individually or use a smaller batch.');}finally{if(id===generation.current){working.current=false;onBusy(false);setZipBusy(false);}}
 }
 useEffect(()=>{const cleanup=()=>{generation.current++;controller.current?.abort();for(const row of queue.current)if(row.result)URL.revokeObjectURL(row.result.url);if(zipRef.current)URL.revokeObjectURL(zipRef.current.url);};const stopDrop=e=>e.preventDefault();window.addEventListener('dragover',stopDrop);window.addEventListener('drop',stopDrop);window.addEventListener('pagehide',cleanup);return()=>{cleanup();window.removeEventListener('dragover',stopDrop);window.removeEventListener('drop',stopDrop);window.removeEventListener('pagehide',cleanup);};},[]);
 actions.current={kind,target,busy:busy||zipBusy,count:items.length,change:next=>{releaseResults();setTarget(next);setStatus('');}};
 useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=t=>{try{Promise.resolve(context.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'get_converter_options',description:'Read supported formats and selection count. Does not expose file contents or names.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({categories,maxBatchBytes:BATCH_LIMIT,current:{category:actions.current.kind,format:actions.current.target,count:actions.current.count,busy:actions.current.busy}})});register({name:'set_output_format',description:'Select an output format and clear previous results. Does not convert or download.',inputSchema:{type:'object',properties:{format:{type:'string'}},required:['format'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async({format})=>{const s=actions.current;if(s.busy)throw new Error('Conversion in progress.');if(!categories[s.kind].outputs.includes(format))throw new Error('Unsupported format.');s.change(format);await new Promise(r=>setTimeout(r,0));return{format:actions.current.target};}});return()=>lifecycle.abort();},[]);
 const locked=busy||zipBusy;
 return <><div className="page-heading"><div className="eyebrow blue">A LITTLE CHANGE. ALL YOURS.</div><h1>New format. <span>Zero uploads.</span></h1><p>Drop a batch. Pick a format. Keep every file on your device.</p></div>
 <section className="workspace" aria-label="File converter"><div className="workspace-title"><div className="section-icon"><Icon size={21}/></div><div><h2>{config.label} converter</h2><p>{config.description}</p></div><span className="local-badge"><HardDrive size={14}/> ON DEVICE</span></div>
 <div className="conversion-grid"><div><div className="step-label"><span>01</span> Choose your files</div><input ref={input} id="file-input" type="file" multiple accept={config.inputs.map(x=>'.'+x).join(',')} onChange={e=>{add(e.target.files);e.target.value='';}} hidden/>
 <button disabled={locked} className={'dropzone '+(dragging?'dragging':'')+(items.length?' compact-drop':'')} onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();if(!locked)setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);add(e.dataTransfer.files);}}><span className="upload-icon"><Upload size={28}/></span><strong>{items.length?'Drop more files here':'Drag & drop your files'}</strong><span>or <b>select multiple files</b></span><span className="format-hint">{config.inputs.slice(0,5).map(x=>x.toUpperCase()).join(', ')}{config.inputs.length>5?' + more':''}<br/>500 MB per batch · {config.limit} MB per file</span></button>
 <div className="batch-meter"><div><span>{items.length} {items.length===1?'file':'files'} selected</span><strong>{bytes(total)} / 500 MB</strong></div><progress max={BATCH_LIMIT} value={total} aria-label="Selected file size"/></div><div className="input-footnote"><ShieldCheck size={15}/> Your files never leave this browser.</div></div>
 <div className="output-column"><div className="step-label"><span>02</span> Make it yours</div><label className="field-label" htmlFor="output-format">Convert all to</label><div className="select-wrap"><span className="format-square">{target.toUpperCase()}</span><select id="output-format" value={target} disabled={locked} onChange={e=>actions.current.change(e.target.value)}>{config.outputs.map(format=><option key={format} value={format}>{formatNames[format]}</option>)}</select><ChevronDown size={16}/></div>
 {kind!=='documents'&&<><label className="field-label quality-label" htmlFor="quality">Quality</label><div className="quality-select"><select id="quality" disabled={locked} value={quality} onChange={e=>{releaseResults();setQuality(e.target.value);}}><option value="balanced">Balanced</option><option value="high">High quality</option><option value="small">Smaller file</option></select></div></>}
 <div className="conversion-note"><Info size={16}/><p>{kind==='documents'?'Text-first conversion. Complex layouts, images and tables are simplified.':kind==='images'?'Image dimensions are preserved. Use Tools to resize, frame, or place images into Word documents.':kind==='audio'&&['mp4','mov'].includes(target)?'Audio becomes a video with a plain navy background.':'Files are processed one at a time. Keep this tab open until conversion finishes.'}</p></div>
 <div className="convert-action">{busy?<button className="primary-button cancel-button" onClick={cancel}><X size={18}/> Stop conversion</button>:<button className="primary-button" disabled={!pending.length||zipBusy} onClick={start}><ArrowRightLeft size={18}/>{items.some(x=>x.result)?'Convert remaining':`Convert ${items.length>1?'all files':'file'}`}</button>}<span>{ready.length?`${ready.length} of ${items.length} ready to download`:'500 MB total input · No file uploads'}</span></div>
 {ready.length>1&&<div className="zip-action">{zip?<a href={zip.url} download="local-converted-files.zip" className="secondary-button"><Download size={16}/> Download ZIP ({bytes(zip.size)})</a>:<button className="secondary-button" disabled={locked} onClick={prepareZip}>{zipBusy?<LoaderCircle size={16} className="spin"/>:<Download size={16}/>} {zipBusy?'Preparing ZIP…':'Prepare all as ZIP'}</button>}</div>}
 </div></div>
 {(status||error)&&<div className={'feedback '+(error?'error':'')} role={error?'alert':'status'}>{locked?<LoaderCircle size={18} className="spin"/>:<Info size={18}/>}<span>{error||status}</span></div>}
 {!!items.length&&<div className="queue-list" aria-label="Selected files">{items.map(row=><div className={'queue-row '+row.state} key={row.id}><div className="queue-icon">{row.state==='converting'?<LoaderCircle className="spin" size={20}/>:row.state==='done'?<Check size={20}/>:<Icon size={20}/>}</div><div className="queue-file"><strong title={row.file.name}>{row.file.name}</strong><span>{bytes(row.file.size)} · {row.state==='done'?`Ready · ${bytes(row.result.size)}`:row.state==='error'?'Failed':row.state==='converting'?'Converting':'Waiting'}</span>{row.error&&<p role="alert">{row.error}</p>}</div>{row.result&&<a className="queue-download" href={row.result.url} download={row.result.name} aria-label={`Download ${row.result.name}`}><Download size={18}/><span>{target.toUpperCase()}</span></a>}<button className="icon-button" disabled={locked} aria-label={`Remove ${row.file.name}`} onClick={()=>remove(row.id)}><X size={17}/></button></div>)}</div>}
 {ready.length===1&&items.length===1&&ready[0].result.type.startsWith('audio/')&&<div className="output-preview"><audio controls src={ready[0].result.url}/></div>}
 {ready.length===1&&items.length===1&&ready[0].result.type.startsWith('video/')&&target!=='mov'&&<div className="output-preview"><video controls src={ready[0].result.url}/></div>}
 <div className="workspace-bottom"><span><Lock size={14}/> Files stay in temporary browser memory</span><button disabled={!items.length&&!error} onClick={clear}><Trash2 size={14}/> Clear files</button></div></section>
 <div className="support-grid"><section className="supported-panel"><div className="small-heading"><h3>A format for what’s next.</h3><button onClick={showFormats}>See supported formats <Plus size={15}/></button></div><div className="format-tiles">{config.outputs.slice(0,4).map(format=><button className={'format-tile '+(target===format?'chosen':'')} key={format} disabled={locked} onClick={()=>actions.current.change(format)}><span>{format.toUpperCase()}</span><p>{formatNames[format]}</p></button>)}</div></section><section className="privacy-card"><span className="privacy-card-icon"><ShieldCheck size={22}/></span><h3>Nothing uploaded.<br/>Nothing kept by us.</h3><p>No conversion history. No cloud copies. Download what you need, then clear your files.</p></section></div></>;
}
