import React,{useMemo,useState} from 'react';
import data from 'emojibase-data/en/data.json';
import {Search,Copy,Check,Smile} from 'lucide-react';
const emojiData=[...new Map(data.filter(item=>item.group!==undefined).map(item=>[item.emoji,item])).values()].sort((a,b)=>(a.order||0)-(b.order||0));
const groups=['Smileys & emotion','People & body','Components','Animals & nature','Food & drink','Travel & places','Activities','Objects','Symbols','Flags'];
export default function EmojiLibrary(){const [query,setQuery]=useState(''),[group,setGroup]=useState('all'),[limit,setLimit]=useState(144),[selected,setSelected]=useState(null),[notice,setNotice]=useState('');const filtered=useMemo(()=>emojiData.filter(item=>(group==='all'||item.group===Number(group))&&[item.label,...(item.tags||[]),item.emoji].join(' ').toLowerCase().includes(query.toLowerCase().trim())),[query,group]);
 async function copy(item){setSelected(item);try{await navigator.clipboard.writeText(item.emoji);setNotice(`Copied ${item.label}.`);}catch{setNotice('Clipboard access is unavailable. Select the emoji below and copy it manually.');}}
 return <><div className="emoji-heading"><div><h3>{emojiData.length.toLocaleString()} emojis. Endless expression.</h3><p>Search by name, browse a category, then click to copy.</p></div><Smile size={32}/></div><div className="emoji-filters"><label className="emoji-search"><Search size={19}/><input aria-label="Search emojis" placeholder="Search smile, heart, coffee…" value={query} onChange={e=>{setQuery(e.target.value);setLimit(144);}}/></label><select aria-label="Emoji category" value={group} onChange={e=>{setGroup(e.target.value);setLimit(144);}}><option value="all">All categories</option>{groups.map((name,i)=><option value={i} key={name}>{name}</option>)}</select></div>{selected&&<div className="emoji-selection" role="status"><input aria-label="Selected emoji to copy" readOnly value={selected.emoji} onFocus={e=>e.target.select()}/><div><strong>{selected.label}</strong><p>{notice}</p></div></div>}<p className="emoji-count">{filtered.length.toLocaleString()} matching emojis</p><div className="emoji-grid">{filtered.slice(0,limit).map(item=><button key={item.hexcode} title={item.label} aria-label={`Copy ${item.label}`} onClick={()=>copy(item)}>{item.emoji}</button>)}</div>{!filtered.length&&<p className="tool-empty">No matches. Try a different word or category.</p>}{filtered.length>limit&&<button className="secondary-button load-emojis" onClick={()=>setLimit(limit+144)}>Show more ({Math.min(limit,filtered.length)} of {filtered.length})</button>}<p className="muted-note">Emoji appearance depends on your device. Older devices may not display newer characters. Data: Emojibase / Unicode.</p></>;
}
