import React,{useState,useRef,useEffect,lazy,Suspense} from 'react';
import {createRoot} from 'react-dom/client';
import {FileText,Image as ImageIcon,AudioLines,Clapperboard,ShieldCheck,Plus,Lock,X,Wrench,LoaderCircle} from 'lucide-react';
import {categories} from './catalog';
import Converter from './Converter';
import './styles.css';
const Tools=lazy(()=>import('./Tools'));
const icons={documents:FileText,images:ImageIcon,audio:AudioLines,video:Clapperboard};
function App(){
 const [kind,setKind]=useState('documents'),[busy,setBusy]=useState(false),[modal,setModal]=useState(null);
 const dialogRef=useRef(null),restoreFocus=useRef(null);
 useEffect(()=>{if(modal){restoreFocus.current=document.activeElement;dialogRef.current?.showModal();}else if(dialogRef.current?.open){dialogRef.current.close();restoreFocus.current?.focus();}},[modal]);
 return <div className="app-shell"><aside className="sidebar"><a className="brand" href="/" aria-label="Local home"><span className="brand-symbol">l<span/></span>local<span className="brand-period">.</span></a><div className="sidebar-group"><p className="eyebrow">YOUR CONVERSION SPACE</p><nav aria-label="Workspace sections">{Object.entries(categories).map(([key,c])=>{const Icon=icons[key];return <button key={key} disabled={busy} className={'nav-item '+(kind===key?'active':'')} aria-current={kind===key?'page':undefined} onClick={()=>setKind(key)}><Icon size={20}/><span>{c.label}</span>{kind===key&&<span className="active-mark"/>}</button>;})}<button disabled={busy} className={'nav-item tools-nav '+(kind==='tools'?'active':'')} aria-current={kind==='tools'?'page':undefined} onClick={()=>setKind('tools')}><Wrench size={20}/><span>Tools</span>{kind==='tools'&&<span className="active-mark"/>}</button></nav></div><div className="sidebar-bottom"><div className="private-icon"><ShieldCheck size={25}/></div><h3>Your files stay yours.</h3><p>Conversion happens right here, on your device.</p><button className="text-button" onClick={()=>setModal('privacy')}>Our privacy promise <Plus size={15}/></button><div className="local-status"><span className="status-dot"/> Local processing only</div></div></aside><div className="main-shell"><header className="topbar"><div className="breadcrumb">Workspace <span>/</span><strong>{kind==='tools'?'Tools':categories[kind].label}</strong></div><button className="privacy-pill" onClick={()=>setModal('privacy')}><Lock size={14}/> Private by design</button></header><main>{kind==='tools'?<Suspense fallback={<div className="loading-tools"><LoaderCircle className="spin"/> Opening your toolbox…</div>}><Tools onBusy={setBusy}/></Suspense>:<Converter key={kind} kind={kind} onBusy={setBusy} showFormats={()=>setModal('formats')}/>}<footer><span>Made to convert. Built to respect your privacy.</span><div><button onClick={()=>setModal('privacy')}>How it works</button><span>·</span><button onClick={()=>setModal('formats')}>Format guide</button></div></footer></main></div>
  <dialog ref={dialogRef} onCancel={e=>{e.preventDefault();setModal(null);}} onClick={e=>{if(e.target===e.currentTarget)setModal(null);}} aria-labelledby="dialog-title"><div className="dialog-content"><button className="dialog-close" aria-label="Close dialog" onClick={()=>setModal(null)}><X size={22}/></button><ShieldCheck className="blue" size={30}/><h2 id="dialog-title">{modal==='privacy'?'Your files stay with you.':'Choose the right format.'}</h2>{modal==='privacy'?<><p>Local converts selected files inside this browser. Their contents and names are never sent to a conversion server.</p><ul><li><strong>Temporary memory only.</strong> We do not use cookies, local storage, IndexedDB or a file history to store your files.</li><li><strong>You control the download.</strong> Only clicking Download saves the result to your device. Clear files releases the app’s references to both input and output; closing the tab ends the session.</li><li><strong>No external conversion service.</strong> Bundled open-source libraries do the work on your device, including FFmpeg for media and Tesseract for text recognition. OCR language data is served from this site; OCR caching is disabled. No separate app is needed.</li><li><strong>The website still loads over the internet.</strong> Site assets and the media engine are fetched from this site. Hosting infrastructure may keep ordinary request logs. Selected file contents are never included.</li></ul><p className="muted">Memory is managed by your browser; secure erasure of RAM or files you download cannot be guaranteed. Your original file remains untouched.</p></>:<><p><strong>Batch conversion:</strong> Select or drop multiple files. The combined input limit is 500 MB (500,000,000 bytes); per-file limits still apply. Files convert sequentially. Failed files do not stop the rest. Download results individually or prepare a ZIP.</p><div className="guide-table">{Object.entries(categories).map(([key,c])=><div key={key}><h3>{c.label} <small>Up to {c.limit} MB</small></h3><p><strong>From</strong> {c.inputs.map(x=>x.toUpperCase()).join(', ')}</p><p><strong>To</strong> {c.outputs.map(x=>x.toUpperCase()).join(', ')}</p></div>)}</div><p><strong>Documents:</strong> Word means DOCX, not legacy DOC. The document converter requires selectable PDF text. Use Tools → Image to text for OCR of pictures. Password-protected PDFs are not supported. Layouts, embedded images and tables are not preserved. Non-Latin text exports to PDF as page images, so that text is not selectable.</p><p><strong>Images:</strong> Static images only, up to 32 megapixels. Quality changes affect JPEG and WebP; PNG is lossless.</p><p><strong>Media:</strong> Actual support depends on the codecs inside the file. MP4 and MOV from audio include a plain video background. Media conversions stop after 5 minutes of processing; use smaller files on mobile. Not every possible format or codec is supported.</p></>}</div></dialog>
</div>;}
createRoot(document.getElementById('root')).render(<App/>);
