import React,{useState,useRef,useEffect,lazy,Suspense} from 'react';
import {Maximize,Frame,FileImage,ScanText,Type,Smile,Upload,Download,Trash2,Plus,X,LoaderCircle,Info,ChevronLeft,ArrowUp,ArrowDown} from 'lucide-react';
import {bytes} from './catalog';
import {IMAGE_ACCEPT,openImage,validateImage,drawImage,canvasBlob,imageDocument,validDimensions} from './image-tools';
import {BATCH_LIMIT} from './batch';
import '@fontsource/inter/latin-400.css';
import '@fontsource/lora/latin-400.css';
import '@fontsource/roboto-mono/latin-400.css';
import '@fontsource/playfair-display/latin-400.css';
import '@fontsource/space-grotesk/latin-400.css';
import '@fontsource/abril-fatface/latin-400.css';
import '@fontsource/anton/latin-400.css';
import '@fontsource/arvo/latin-400.css';
import '@fontsource/bebas-neue/latin-400.css';
import '@fontsource/bitter/latin-400.css';
import '@fontsource/caveat/latin-400.css';
import '@fontsource/cormorant-garamond/latin-400.css';
import '@fontsource/crimson-text/latin-400.css';
import '@fontsource/dancing-script/latin-400.css';
import '@fontsource/dm-sans/latin-400.css';
import '@fontsource/eb-garamond/latin-400.css';
import '@fontsource/figtree/latin-400.css';
import '@fontsource/fira-code/latin-400.css';
import '@fontsource/great-vibes/latin-400.css';
import '@fontsource/inconsolata/latin-400.css';
import '@fontsource/indie-flower/latin-400.css';
import '@fontsource/kalam/latin-400.css';
import '@fontsource/lato/latin-400.css';
import '@fontsource/libre-baskerville/latin-400.css';
import '@fontsource/lobster/latin-400.css';
import '@fontsource/manrope/latin-400.css';
import '@fontsource/merriweather/latin-400.css';
import '@fontsource/montserrat/latin-400.css';
import '@fontsource/nunito/latin-400.css';
import '@fontsource/open-sans/latin-400.css';
import '@fontsource/oswald/latin-400.css';
import '@fontsource/pacifico/latin-400.css';
import '@fontsource/patrick-hand/latin-400.css';
import '@fontsource/poppins/latin-400.css';
import '@fontsource/pt-serif/latin-400.css';
import '@fontsource/quicksand/latin-400.css';
import '@fontsource/raleway/latin-400.css';
import '@fontsource/righteous/latin-400.css';
import '@fontsource/roboto/latin-400.css';
import '@fontsource/rubik/latin-400.css';
import '@fontsource/sacramento/latin-400.css';
import '@fontsource/satisfy/latin-400.css';
import '@fontsource/source-code-pro/latin-400.css';
import '@fontsource/ubuntu/latin-400.css';
import '@fontsource/work-sans/latin-400.css';
const EmojiLibrary=lazy(()=>import('./emojis'));
const tools=[['resize','Image size','Resize dimensions and adjust file size.',Maximize],['frames','Image frames','Preview and export the perfect crop.',Frame],['documents','Images to documents','Make a PDF or Word document.',FileImage],['ocr','Image to text','Extract writing into an editable TXT file.',ScanText],['fonts','Font studio','A writing space with a different voice.',Type],['emoji','Emoji library','Find and copy over 1,000 emojis.',Smile]];
export default function Tools({onBusy}){const [active,setActive]=useState('resize'),[busy,setBusy]=useState(false);const selected=tools.find(x=>x[0]===active);const setWorking=value=>{setBusy(value);onBusy(value);};useEffect(()=>()=>onBusy(false),[]);return <><div className="page-heading"><div className="eyebrow blue">MORE POSSIBILITIES. SAME PRIVACY.</div><h1>Your everyday <span>toolbox.</span></h1><p>Fine-tune images, turn pictures into words, and make room for expression.</p></div><div className="tool-tabs" role="tablist" aria-label="Tools">{tools.map(([key,label,description,Icon])=><button role="tab" id={'tab-'+key} aria-controls="tool-panel" aria-selected={active===key} disabled={busy} className={active===key?'selected':''} onClick={()=>setActive(key)} key={key}><Icon size={20}/><span>{label}</span></button>)}</div><section className="workspace tool-workspace" role="tabpanel" id="tool-panel" aria-labelledby={'tab-'+active}><div className="workspace-title"><div className="section-icon">{React.createElement(selected[3],{size:22})}</div><div><h2>{selected[1]}</h2><p>{selected[2]}</p></div><span className="local-badge">ON DEVICE</span></div><div className="tool-body" key={active}>{active==='resize'||active==='frames'?<ImageEditor mode={active} onBusy={setWorking}/>:active==='documents'?<ImageDocuments onBusy={setWorking}/>:active==='ocr'?<ImageOCR onBusy={setWorking}/>:active==='fonts'?<FontStudio onBusy={setWorking}/>:<Suspense fallback={<p>Loading emoji library…</p>}><EmojiLibrary/></Suspense>}</div></section><p className="tool-privacy">Your work stays in temporary browser memory. Switching tools clears that tool’s files and results.</p></>;}
function DropImages({onFiles,multiple=false,label='Drop an image here',disabled=false}){const ref=useRef(null),[drag,setDrag]=useState(false);return <><input ref={ref} type="file" accept={IMAGE_ACCEPT} multiple={multiple} hidden onChange={e=>{onFiles(Array.from(e.target.files));e.target.value='';}}/><button disabled={disabled} className={'tool-drop '+(drag?'dragging':'')} onClick={()=>ref.current.click()} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(!disabled)onFiles(Array.from(e.dataTransfer.files));}}><Upload size={22}/><strong>{label}</strong><span>or browse · PNG, JPG, WebP, BMP · 30 MB each</span></button></>;}
function Message({error,status,busy}){if(!error&&!status)return null;return <div className={'tool-message '+(error?'error':'')} role={error?'alert':'status'}>{busy?<LoaderCircle size={17} className="spin"/>:<Info size={17}/>}<span>{error||status}</span></div>;}
function useOutput(){const [output,setOutput]=useState(null),ref=useRef(null);function clear(){if(ref.current)URL.revokeObjectURL(ref.current.url);ref.current=null;setOutput(null);}function create(blob,name){clear();const next={url:URL.createObjectURL(blob),name,size:blob.size};ref.current=next;setOutput(next);}useEffect(()=>()=>{if(ref.current)URL.revokeObjectURL(ref.current.url);},[]);return{output,create,clear};}
function DownloadOutput({output}){return output?<a className="primary-button success-button" download={output.name} href={output.url}><Download size={17}/> Download · {bytes(output.size)}</a>:null;}
function useImage(){const [source,setSource]=useState(null),ref=useRef(null),generation=useRef(0);function clear(){generation.current++;if(ref.current)URL.revokeObjectURL(ref.current.url);ref.current=null;setSource(null);}async function load(file){const id=++generation.current;const item=await openImage(file);if(id!==generation.current){URL.revokeObjectURL(item.url);return null;}if(ref.current)URL.revokeObjectURL(ref.current.url);ref.current=item;setSource(item);return item;}useEffect(()=>()=>{generation.current++;if(ref.current)URL.revokeObjectURL(ref.current.url);},[]);return{source,load,clear};}
function ImageEditor({mode,onBusy}){
 const {source,load,clear:clearImage}=useImage(),{output,create,clear:clearOutput}=useOutput();
 const [width,setWidth]=useState(1280),[height,setHeight]=useState(720),[locked,setLocked]=useState(true),[format,setFormat]=useState('image/jpeg'),[quality,setQuality]=useState(85),[ratio,setRatio]=useState('1:1'),[fit,setFit]=useState('cover'),[x,setX]=useState(50),[y,setY]=useState(50),[background,setBackground]=useState('#ffffff'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const frame=mode==='frames',parts=ratio.split(':').map(Number),frameHeight=Math.round(Number(width)*parts[1]/parts[0]);
 async function select(files){if(files.length!==1){setError('Choose one image for this tool.');return;}setError('');setBusy(true);onBusy(true);clearOutput();try{const img=await load(files[0]);if(img){setWidth(frame?1280:img.width);setHeight(img.height);}}catch(e){setError(e.message);}finally{setBusy(false);onBusy(false);}}
 function changeWidth(value){clearOutput();setWidth(value);if(locked&&source&&!frame)setHeight(Math.max(1,Math.round(Number(value)*source.height/source.width)));}
 function changeHeight(value){clearOutput();setHeight(value);if(locked&&source)setWidth(Math.max(1,Math.round(Number(value)*source.width/source.height)));}
 async function generate(){if(!source)return;setBusy(true);onBusy(true);setError('');try{const w=Number(width),h=frame?frameHeight:Number(height);validDimensions(w,h);const canvas=drawImage(source.image,{width:w,height:h,fit:frame?fit:'stretch',x:Number(x),y:Number(y),background});try{const blob=await canvasBlob(canvas,format,Number(quality)/100);create(blob,source.file.name.replace(/\.[^.]+$/,'')+(frame?'-framed':'-resized')+'.'+format.split('/')[1].replace('jpeg','jpg'));}finally{canvas.width=canvas.height=0;}}catch(e){setError(e.message);}finally{setBusy(false);onBusy(false);}}
 return <><DropImages onFiles={select} disabled={busy} label={source?'Drop a replacement image':'Drop an image here'}/>{source?<div className="tool-editor-grid"><div><div className={'image-stage '+(frame?'frame-stage':'')} style={frame?{aspectRatio:parts[0]/parts[1],background}:undefined}><img src={source.url} alt="Selected image preview" style={frame?{objectFit:fit,objectPosition:`${x}% ${y}%`}:undefined}/></div><p className="image-meta">{source.width} × {source.height} px · {bytes(source.file.size)}</p>{output&&<p className="image-meta">Output: {Number(width)} × {frame?frameHeight:Number(height)} px · {bytes(output.size)}{output.size<source.file.size?` · ${Math.round((1-output.size/source.file.size)*100)}% smaller`:''}</p>}</div><fieldset className="tool-controls" disabled={busy}>
 {frame?<><label>Frame ratio<select value={ratio} disabled={busy} onChange={e=>{clearOutput();setRatio(e.target.value);}}>{['1:1','4:5','16:9','9:16','16:4','3:2'].map(r=><option key={r}>{r}</option>)}</select></label><label>Image fit<select value={fit} disabled={busy} onChange={e=>{clearOutput();setFit(e.target.value);}}><option value="cover">Fill frame (crop edges)</option><option value="contain">Fit entire image</option></select></label><label>Horizontal position: {x}%<input type="range" min="0" max="100" value={x} onChange={e=>{clearOutput();setX(e.target.value);}}/></label><label>Vertical position: {y}%<input type="range" min="0" max="100" value={y} onChange={e=>{clearOutput();setY(e.target.value);}}/></label><label>Background<input type="color" value={background} onChange={e=>{clearOutput();setBackground(e.target.value);}}/></label></>:<label className="checkbox-label"><input type="checkbox" checked={locked} onChange={e=>setLocked(e.target.checked)}/> Keep original proportions</label>}
 <div className="field-pair"><label>{frame?'Export width':'Width'} (px)<input type="number" min="1" max="8000" value={width} onChange={e=>changeWidth(e.target.value)}/></label><label>Height (px)<input type="number" min="1" max="8000" value={frame?frameHeight:height} readOnly={frame} onChange={e=>changeHeight(e.target.value)}/></label></div><label>Output format<select value={format} onChange={e=>{clearOutput();setFormat(e.target.value);}}><option value="image/jpeg">JPEG</option><option value="image/png">PNG (lossless)</option><option value="image/webp">WebP</option></select></label>{format!=='image/png'&&<label>Quality: {quality}%<input type="range" min="10" max="100" value={quality} onChange={e=>{clearOutput();setQuality(e.target.value);}}/></label>}<p className="muted-note">Smaller dimensions and lower JPEG/WebP quality reduce file size. Actual size appears after export. Transparent areas use a solid background.</p><button className="primary-button" disabled={busy} onClick={generate}>{busy?<LoaderCircle className="spin" size={17}/>:<Download size={17}/>} Create {frame?'framed':'resized'} image</button><DownloadOutput output={output}/><button className="secondary-button" disabled={busy} onClick={()=>{clearImage();clearOutput();setError('');}}><Trash2 size={16}/> Clear image</button></fieldset></div>:<div className="tool-empty"><Frame size={35}/><p>{frame?'See your image in square, portrait, widescreen and banner formats.':'Set precise dimensions, adjust compression and see the resulting file size.'}</p></div>}<Message error={error}/></>;
}
function ImageDocuments({onBusy}){const [files,setFiles]=useState([]),[format,setFormat]=useState('pdf'),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);const {output,create,clear}=useOutput(),controller=useRef(null),generation=useRef(0);useEffect(()=>()=>{generation.current++;controller.current?.abort();},[]);
 function add(list){if(busy)return;try{if([...files,...list].reduce((n,f)=>n+f.size,0)>BATCH_LIMIT)throw new Error('The combined selection must be 500 MB or less.');for(const file of list)validateImage(file);clear();setFiles([...files,...list]);setError('');setStatus('');}catch(e){setError(e.message);}}
 function reorder(index,direction){clear();setFiles(old=>{const next=[...old];[next[index],next[index+direction]]=[next[index+direction],next[index]];return next;});}
 async function generate(){if(!files.length||busy)return;const id=++generation.current;const aborter=new AbortController();controller.current=aborter;setBusy(true);onBusy(true);setError('');clear();try{const blob=await imageDocument(files,format,{signal:aborter.signal,onStatus:s=>{if(id===generation.current)setStatus(s);}});if(id===generation.current)create(blob,'local-images.'+format);}catch(e){if(id===generation.current&&!aborter.signal.aborted)setError(e.message);}finally{if(id===generation.current){setBusy(false);onBusy(false);setStatus('');}}}
 function cancel(){generation.current++;controller.current?.abort();setBusy(false);onBusy(false);setStatus('Conversion cancelled.');}
 return <><DropImages multiple onFiles={add} disabled={busy} label="Drop one or more images"/><div className="batch-meter"><div><span>{files.length} images · one image per page</span><strong>{bytes(files.reduce((n,f)=>n+f.size,0))} / 500 MB</strong></div></div><div className="image-doc-list">{files.map((file,i)=><div className="image-doc-row" key={i}><span className="page-number">{i+1}</span><span className="image-doc-name">{file.name}<small>{bytes(file.size)}</small></span><button className="icon-button" aria-label={`Move ${file.name} up`} disabled={busy||i===0} onClick={()=>reorder(i,-1)}><ArrowUp size={16}/></button><button className="icon-button" aria-label={`Move ${file.name} down`} disabled={busy||i===files.length-1} onClick={()=>reorder(i,1)}><ArrowDown size={16}/></button><button className="icon-button" disabled={busy} aria-label={`Remove ${file.name}`} onClick={()=>{clear();setFiles(files.filter((_,n)=>n!==i));}}><X size={16}/></button></div>)}</div><div className="document-actions"><label>Document format<select value={format} disabled={busy} onChange={e=>{clear();setFormat(e.target.value);}}><option value="pdf">PDF</option><option value="docx">Word DOCX</option></select></label><button disabled={!files.length||busy} className="primary-button" onClick={generate}><FileImage size={18}/> Create {format.toUpperCase()}</button>{busy&&<button className="secondary-button" onClick={cancel}>Cancel</button>}<DownloadOutput output={output}/><button disabled={busy||!files.length} className="secondary-button" onClick={()=>{setFiles([]);clear();setError('');setStatus('');}}><Trash2 size={16}/> Clear images</button></div><p className="muted-note">Images are fitted to A4 pages without cropping. The DOCX contains pictures, not editable extracted text. Use Image to text for editable writing. Large images are scaled to a 2,000-pixel longest edge in the document.</p><Message error={error} status={status} busy={busy}/></>;
}
function ImageOCR({onBusy}){const {source,load,clear:clearImage}=useImage(),{output,create,clear:clearOutput}=useOutput();const [language,setLanguage]=useState('eng'),[text,setText]=useState(''),[confidence,setConfidence]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('');const controller=useRef(null),generation=useRef(0);useEffect(()=>()=>{generation.current++;controller.current?.abort();},[]);
 async function select(files){if(files.length!==1){setError('Choose one image to read.');return;}setBusy(true);onBusy(true);setError('');clearOutput();setText('');setConfidence(null);try{await load(files[0]);}catch(e){setError(e.message);}finally{setBusy(false);onBusy(false);}}
 async function recognize(){if(!source||busy)return;const id=++generation.current,aborter=new AbortController();controller.current=aborter;setBusy(true);onBusy(true);setError('');clearOutput();setText('');setConfidence(null);setStatus('Loading local text recognition…');try{const {extractText}=await import('./ocr');const result=await extractText(source.file,language,{signal:aborter.signal,onStatus:s=>{if(id===generation.current)setStatus(s);}});if(id!==generation.current)return;setText(result.text);setConfidence(Math.round(result.confidence));setStatus(result.text.trim()?'Text extracted. Review and correct it before downloading.':'No text found. Try a sharper image with larger writing.');}catch(e){if(id===generation.current&&!aborter.signal.aborted){setError('Text recognition failed. Try a smaller, clearer image. '+(e.message||''));setStatus('');}}finally{if(id===generation.current){setBusy(false);onBusy(false);}}}
 function cancel(){generation.current++;controller.current?.abort();setBusy(false);onBusy(false);setStatus('Cancelled. Any engine download already started may finish in memory.');}
 return <><DropImages onFiles={select} disabled={busy} label="Drop a photo of writing"/><div className="tool-editor-grid"><div>{source?<img className="ocr-preview" src={source.url} alt="Image to extract text from"/>:<div className="tool-empty"><ScanText size={40}/><p>Printed pages, screenshots, labels or handwritten notes.</p></div>}<p className="muted-note">Best for clear printed text. Handwriting, shadows and complex layouts can produce mistakes. Review the result; accuracy is not guaranteed.</p><label className="tool-label">Language<select disabled={busy} value={language} onChange={e=>setLanguage(e.target.value)}><option value="eng">English</option><option value="hin">Hindi</option><option value="eng+hin">English + Hindi</option></select></label><button className="primary-button" disabled={!source||busy} onClick={recognize}><ScanText size={17}/> Extract text locally</button>{busy&&<button className="secondary-button" onClick={cancel}>Cancel recognition</button>}</div><div className="tool-controls"><label>Extracted text {confidence!==null&&<span className="confidence">· Engine confidence {confidence}%</span>}<textarea className="extracted-text" value={text} disabled={busy} onChange={e=>{clearOutput();setText(e.target.value);}} placeholder="Extracted writing will appear here. You can edit it before saving."/></label><button disabled={!text.trim()||busy} className="primary-button" onClick={()=>create(new Blob([text],{type:'text/plain;charset=utf-8'}),'extracted-text.txt')}><FileImage size={17}/> Prepare TXT download</button><DownloadOutput output={output}/><button className="secondary-button" disabled={busy} onClick={()=>{clearImage();clearOutput();setText('');setConfidence(null);setStatus('');setError('');}}><Trash2 size={16}/> Clear image and text</button></div></div><Message error={error} status={status} busy={busy}/></>;
}
const fontOptions=["Inter","Lora","Roboto Mono","Playfair Display","Space Grotesk","Arial","Georgia","Times New Roman","Courier New","Abril Fatface","Anton","Arvo","Bebas Neue","Bitter","Caveat","Cormorant Garamond","Crimson Text","DM Sans","Dancing Script","EB Garamond","Figtree","Fira Code","Great Vibes","Inconsolata","Indie Flower","Kalam","Lato","Libre Baskerville","Lobster","Manrope","Merriweather","Montserrat","Nunito","Open Sans","Oswald","PT Serif","Pacifico","Patrick Hand","Poppins","Quicksand","Raleway","Righteous","Roboto","Rubik","Sacramento","Satisfy","Source Code Pro","Ubuntu","Work Sans"];
function FontStudio({onBusy}){const [text,setText]=useState(''),[font,setFont]=useState('Inter'),[size,setSize]=useState(24),[bold,setBold]=useState(false),[italic,setItalic]=useState(false),[color,setColor]=useState('#233451'),[busy,setBusy]=useState(false),[error,setError]=useState('');const {output,create,clear}=useOutput();const style={fontFamily:font,fontSize:`${size}px`,fontWeight:bold?700:400,fontStyle:italic?'italic':'normal',color};
 async function exportWord(){if(!text.trim()||busy)return;setBusy(true);onBusy(true);setError('');try{const {Document,Packer,Paragraph,TextRun}=await import('docx');const blob=await Packer.toBlob(new Document({creator:'',sections:[{children:text.split('\n').map(line=>new Paragraph({children:[new TextRun({text:line,font,size:Math.round(Number(size)*1.5),bold,italics:italic,color:color.slice(1)})]}))}]}));create(blob,'my-writing.docx');}catch(e){setError('Could not create the document.');}finally{setBusy(false);onBusy(false);}}
 return <><fieldset className="font-toolbar" disabled={busy}><label>Font<select value={font} disabled={busy} onChange={e=>{clear();setFont(e.target.value);}}>{fontOptions.map(f=><option key={f} value={f}>{f}</option>)}</select></label><label>Size: {size}px<input type="range" min="12" max="72" value={size} onChange={e=>{clear();setSize(e.target.value);}}/></label><button className={'style-toggle '+(bold?'selected':'')} aria-pressed={bold} aria-label="Bold" onClick={()=>{clear();setBold(!bold);}}><b>B</b></button><button className={'style-toggle '+(italic?'selected':'')} aria-pressed={italic} aria-label="Italic" onClick={()=>{clear();setItalic(!italic);}}><i>I</i></button><label>Text color<input type="color" value={color} onChange={e=>{clear();setColor(e.target.value);}}/></label></fieldset><textarea aria-label="Writing area" className="writing-area" maxLength={50000} value={text} style={style} placeholder="A little space for your next big idea…" disabled={busy} onChange={e=>{clear();setText(e.target.value);}}/><div className="writing-meta"><span>{text.trim()?text.trim().split(/\s+/).length:0} words · {text.length.toLocaleString()} / 50,000 characters</span><span>No autosave. Download to keep your writing.</span></div><div className="font-actions"><button className="primary-button" disabled={!text.trim()||busy} onClick={exportWord}>Prepare Word document</button><button className="secondary-button" disabled={!text.trim()||busy} onClick={()=>create(new Blob([text],{type:'text/plain;charset=utf-8'}),'my-writing.txt')}>Prepare plain TXT</button><DownloadOutput output={output}/><button className="secondary-button" disabled={busy} onClick={()=>{setText('');clear();}}>Clear writing</button></div><p className="muted-note">Word output keeps font and styling settings; the receiving device needs that font to render it exactly. Plain TXT keeps the writing only.</p><Message error={error} status={busy?'Creating Word document…':''} busy={busy}/></>;
}
